---
- name: Create configuration for serverless, node, npm, aws cli
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Create ubuntu user
      user:
        name: ubuntu
        state: present
        shell: /bin/bash

    - name: Add ubuntu user to sudo group
      user:
        name: ubuntu
        groups: sudo
        append: yes
      
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install unzip
      apt:
        name: unzip
        state: present


    - name: Download and install NVM
      become: true
      become_user: ubuntu
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: ~/.nvm

    - name: Install Node.js
      become: true
      become_user: ubuntu
      shell: source ~/.nvm/nvm.sh && nvm install --lts
      args:
        executable: /bin/bash
    
    - name: Install serverless framework
      become: true
      become_user: ubuntu
      shell: source ~/.nvm/nvm.sh && npm install -g serverless
      args:
        executable: /bin/bash

    - name: git config
      become: true
      become_user: ubuntu
      shell: git config --global user.email "email" && git config --global user.name "name"
      args:
        executable: /bin/bash
    
    - name: Download and install AWS
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install
      args:
        executable: /bin/bash

    - name: Create ~/.aws directory
      become: true
      become_user: ubuntu
      file:
        path: ~/.aws
        state: directory
        mode: 0700
  
    - name: Create AWS credentials file
      become: true
      become_user: ubuntu
      copy:
        content: |
          [default]
          aws_access_key_id = KEY
          aws_secret_access_key = ACCESS
        dest: ~/.aws/credentials
        mode: 0600

    - name: Create AWS config file
      become: true
      become_user: ubuntu
      copy:
        content: |
          [default]
          region = ap-south-1
        dest: ~/.aws/config
        mode: 0600
